[MeasureState]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=State
UpdateDivider=2

[MeasureStateButton]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=STATE
Substitute="0":"Play","1":"Pause","2":"Play"
UpdateDivider=2

[MeasureCover]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Cover
CoverPath=#@#images\coverGPMDP.png
UpdateDivider=100

[MeasurePosition]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Position
UpdateDivider=20

[MeasureDuration]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Duration
UpdateDivider=20

[MeasureProgress]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Progress
UpdateDivider=20

[MeasureArtist]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Artist
Substitute="":""
UpdateDivider=100

[MeasureAlbum]
Measure=Plugin
Plugin=GPMDPPlugin
PLayerInfo=Album
UpdateDivider=100

[MeasureTrack]
Measure=Plugin
Plugin=GPMDPPlugin
PlayerInfo=Title
UpdateDivider=100