[MeasureState]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=State
UpdateDivider=1

[MeasureStateButton]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=State
Substitute="0":"Play","1":"Pause","2":"Play"
UpdateDivider=1

[MeasureCover]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Cover
Substitute="":"#@#images\#ImageName#"
UpdateDivider=1

[MeasurePosition]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Position
UpdateDivider=20

[MeasureDuration]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Duration
UpdateDivider=20

[MeasureProgress]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Progress
UpdateDivider=20

[MeasureTrack]
Measure=NowPlaying
PlayerName=#PlayerName#
PlayerType=Title
UpdateDivider=100

[MeasureArtist]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Artist
UpdateDivider=100

[MeasureAlbum]
Measure=NowPlaying
PlayerName=#playerName#
PlayerType=Album
UpdateDivider=100